spring:
  cloud:
    stream:
      function:
        definition: data;toUpperCase;consumer
      bindings:
        data-in-0:
          destination: data-in
        data-out-0:
          destination: data-out
        toUpperCase-in-0:
          destination: data-out
        toUpperCase-out-0:
          destination: upper-out
        consumer-in-0:
          destination: upper-out
